### ISSUE TITLE
Question about cylindrical projection

### ISSUE THREAD

**Issue by chenweifu2008** [jonathanventura/cylindricalsfmlearner#1]
Hi Jonathan,
Thank you so much for sharing the code! Can you tell me which part of the code is to project a normal panorama to a cylindrical panorama?

**Comment by jonathanventura** [comment]
Hello, you're welcome and thanks for your interest!

The code for converting an equirectangular panorama to cylindrical is under scripts/unwarp.

I also have a separate repo here which can convert from equirectangular or cubemap: 

[https://github.com/jonathanventura/panorama-converter](https://github.com/jonathanventura/panorama-converter)

In case you want to write your own code to do it, here is a PDF about the various conversions:

[Panorama_Projections.pdf](https://github.com/jonathanventura/cylindricalsfmlearner/files/7606433/Panorama_Projections.pdf)
